"""empty message

Revision ID: 30adcac68f1
Revises: 183ef9b0798
Create Date: 2015-12-05 16:59:52.329599

"""

# revision identifiers, used by Alembic.
revision = '30adcac68f1'
down_revision = '183ef9b0798'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'extension', new_column_name='file_extension')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'file_extension', new_column_name='extension')
    ### end Alembic commands ###
